syntax = "proto3";

package tx;

import "google/api/annotations.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/exc-works/caishen/api/types";

service Block {
  // LatestBlock 返回最新的区块
  rpc LatestBlock(LatestBlockRequest) returns (LatestBlockResponse) {
    option (google.api.http) = {
      get: "/v1/explorer/latest-block"
    };
  }
}

message LatestBlockRequest {}

message LatestBlockResponse {
  BlockResponse block = 1;
}

message BlockResponse {
  uint64 number = 1;
  bytes proposer = 2 [
    (gogoproto.customtype) = "github.com/ethereum/go-ethereum/common.Address",
    (gogoproto.nullable) = false
  ];
  bytes hash = 3 [
    (gogoproto.customtype) = "github.com/ethereum/go-ethereum/common.Hash",
    (gogoproto.nullable) = false
  ];
  int64 time = 4;
  uint64 start_sequence_id = 5;
  uint64 end_sequence_id = 6;
}
