syntax = "proto3";
package share.schema;

option go_package = "github.com/exc-works/caishen/share/schema";

import "schema/extensions.proto";
import "schema/error.proto";
import "schema/order.proto";

enum TxActionType {
  UNKNOWN_TYPE = 0;
  GENESIS = 1;      // 创世交易
  START_BLOCK = 2;  // 开始区块
  END_BLOCK = 3;    // 结束区块

  ENABLE_CHAIN = 10;
  DISABLE_CHAIN = 11;
  REGISTER_TOKEN = 12;    // 注册Token
  DEPOSIT_TOKEN = 13;     // 链上充值
  WITHDRAW_TOKEN = 14;    // 链上提现
  TRANSFER_TOKEN = 15;    // 转账
  CONFIRM_WITHDRAW = 16;  // 确认链上提现
  REJECT_WITHDRAW = 17;   // 拒绝链上提现
  reserved 18 to 20;
  REGISTER_SYMBOL = 21;  // 注册交易对
  reserved 22;           // CLOSE_ENGINE = 22
  UPDATE_SYMBOL = 23;
  PLACE_ORDER = 24;                // 下单
  CANCEL_ORDER = 25;               // 取消订单
  UPDATE_FUNDING_RATE = 26;        // 更新资金费率
  REGISTER_FEE_TIER = 27;          // 注册费率等级
  REGISTER_ACCOUNT_FEE_TIER = 28;  // 设置账户费率等级
  UPDATE_INDEX_PRICE = 29;         // 更新指数价格
  APPROVE_AGENT = 30;              // 授权或取消 Agent
  SET_POSITION_MODE = 31;          // 设置仓位模式
  REGISTER_RISK_LIMITS = 32;       // 注册风险限额
  CANCEL_BATCH_ORDERS = 33;        // 批量取消订单
  SET_POSITION_LEVERAGE = 34;      // 设置仓位杠杆
  CONVERT_TO_MULTISIG = 35;        // 转换地址为多签
  UPDATE_MULTISIG_CONFIG = 36;     // 更新多签配置
  CONVERT_TO_REGULAR = 37;         // 转换多签地址为普通地址
  SETTLE_BATCH_FUNDING_FEES = 38;  // 批量结算资金费
  INCREASE_MARGIN = 39;            // 增加逐仓保证金
  DECREASE_MARGIN = 40;            // 减少逐仓保证金
  TRIGGER_ORDER = 41;              // 执行触发：计划委托、止盈止损、移动止盈止损
  ENTER_LIQUIDATION_MODE = 42;     // 进入清算模式
  EXIT_LIQUIDATION_MODE = 43;      // 退出清算模式
  CANCEL_LIQUIDATION_ORDERS = 44;  // 撤销清算模式下的订单
  LIQUIDATE_POSITION = 45;         // 清算仓位
}

message StartBlockMessage {
  uint64 number = 1;
  int64 time = 2;
}

message EndBlockMessage {
  uint64 number = 1;
  bytes hash = 2 [(schema.hash) = true];
}

// TxMessage 定义了区块链交易的结构
//
// hash = keccak256(chain_id, recent_block_hash, action, target_address, data)
message TxMessage {
  uint64 chain_id = 1;
  bytes recent_block_hash = 2 [(schema.hash) = true];
  TxActionType action = 3;
  bytes target_address = 4 [(schema.address) = true];  // 目标地址
  bytes data = 5;
  // 如果签名为1个，则恢复出来的地址要么为 target_address，要么为agent地址
  //
  // 如果签名为多个，则表示多签
  repeated bytes signatures = 6 [(schema.signatures) = true];
}

message BlockResult {
  uint64 number = 1;
}

message TxResult {
  message CancelLiquidationOrdersResult {
    repeated uint64 ids = 1;           // canceled order ids
    bool exited_liquidation_mode = 2;  // whether exited liquidation mode
  }
  message PlaceOrderResult {
    uint64 id = 1;  // order id
    optional string size = 2 [(schema.decimal) = true];
    optional string filled = 3 [(schema.decimal) = true];
    optional string price = 4 [(schema.decimal) = true];
    optional string filled_price = 5 [(schema.decimal) = true];
    optional bytes client_order_id = 6;
    OrderStatus status = 7;
  }

  bytes tx_hash = 1 [(schema.hash) = true];  // tx hash for matching
  oneof result {
    Error error = 2;
    BlockResult block_result = 3;
  }
  oneof extra {
    CancelLiquidationOrdersResult cancel_liquidation_orders_result = 6;
    PlaceOrderResult place_order_result = 7;
  }  // extra results for special actions
}

message Block {
  uint64 number = 1;
  bytes proposer = 2 [(schema.address) = true];
  bytes hash = 3 [(schema.hash) = true];
  int64 time = 4;
  uint64 start_sequence_id = 5;
  uint64 end_sequence_id = 6;
}
