syntax = "proto3";

package share.schema;

option go_package = "github.com/exc-works/caishen/share/schema";

import "schema/extensions.proto";
import "schema/order.proto";
import "schema/symbol.proto";
import "schema/fee_tier.proto";
import "schema/error.proto";
import "google/protobuf/timestamp.proto";

message ChangesCollector {
  google.protobuf.Timestamp time = 1;

  AssetChange asset_change = 2;
  L2bookChange l2book_change = 3;
  TriggerOrderChange trigger_order_change = 4;

  FundingChange funding_change = 5;
  MetadataChange metadata_change = 6;
  OrderChange order_change = 7;
  PositionChange position_change = 8;
  PriceChange price_change = 9;
}

message BlockChange {
  BlockChangeEntry change = 1;
}

message BlockChangeEntry {
  message BlockStarted {
    uint64 number = 1;
    int64 time = 2;
  }
  message BlockEnded {
    uint64 number = 1;
    bytes hash = 2 [(schema.hash) = true];
  }
  message TxProcessed {

  }

  oneof change {
    BlockStarted block_started = 1;
    BlockEnded block_ended = 2;
    TxProcessed tx_processed = 3;
  }
}

message AssetChange {
  repeated AssetChangeEntry changes = 1;
}

message AssetChangeEntry {
  oneof change {
    Deposited deposited = 1;
    Withdrew withdrew = 2;
    PositionFundingSettled position_funding_settled = 3;
    InsuranceFundingLossCovered insurance_funding_loss_covered = 4;
    OrderPlaced order_placed = 5;
    InsuranceExecutedFeeLossCovered insurance_executed_fee_loss_covered = 6;
    PositionIncreased position_increased = 7;
    PositionDecreased position_decreased = 8;
    InsurancePnLLossCovered insurance_pnl_loss_covered = 9;
    PositionMarginIncreased position_margin_increased = 10;
    PositionMarginDecreased position_margin_decreased = 11;
    TransferIn transfer_in = 12;
    TransferOut transfer_out = 13;
    WithdrewConfirmed withdrew_confirmed = 14;
    WithdrewRejected withdrew_rejected = 15;
    OrderFrozenReleased order_frozen_released = 16;
    PositionLeverageChanged position_leverage_changed = 17;
  }

  message Deposited {
    bytes account = 1 [(schema.address) = true];
    uint32 token_id = 2;
    string wallet_delta = 3 [(schema.decimal) = true];
    string wallet = 4 [(schema.decimal) = true];
    uint32 chain_id = 5;
    bytes deposit_hash = 6;
    bytes idempotency_key = 7;
  }

  message Withdrew {
    bytes account = 1 [(schema.address) = true];
    uint32 token_id = 2;
    string wallet_delta = 3 [(schema.decimal) = true];
    string wallet = 4 [(schema.decimal) = true];
    uint64 pending_id = 5;
  }

  message WithdrewConfirmed {
    uint64 pending_id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 token_id = 3;
    // 提现金额，该值为负数
    string amount = 4 [(schema.decimal) = true];
    bytes hash = 5 [(schema.hash) = true];
  }

  message WithdrewRejected {
    uint64 pending_id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 token_id = 3;
    // 提现金额，该值为正数
    string amount = 4 [(schema.decimal) = true];
    string wallet = 5 [(schema.decimal) = true];
    string reason = 6;
  }

  message TransferOut {
    // 转出账户
    bytes account = 1 [(schema.address) = true];
    // 转入账户
    bytes dst_account = 2 [(schema.address) = true];
    uint32 token_id = 3;
    // 转出金额，该值为负数
    string amount = 4 [(schema.decimal) = true];
    // 转出账户的wallet余额
    string wallet = 5 [(schema.decimal) = true];
  }

  message TransferIn {
    // 转入账户
    bytes account = 1 [(schema.address) = true];
    // 转出账户
    bytes src_account = 2 [(schema.address) = true];
    uint32 token_id = 3;
    // 转入金额，该值为正数
    string amount = 4 [(schema.decimal) = true];
    // 转入账户的wallet余额
    string wallet = 5 [(schema.decimal) = true];
  }

  // 仓位资金费结算事件
  message PositionFundingSettled {
    // position id
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    // 实际的资金费，正数表示收入，负数表示支出
    string amount = 7 [(schema.decimal) = true];
    string wallet = 8 [(schema.decimal) = true];
    string isolated_position_frozen = 9 [(schema.decimal) = true];
  }

  // 保险基金补贴资金费事件
  message InsuranceFundingLossCovered {
    // position id
    uint64 id = 1;
    uint32 base_token = 2;
    uint32 quote_token = 3;
    PositionMode mode = 4;
    PositionSide side = 5;
    string amount = 6 [(schema.decimal) = true];
    string wallet = 7 [(schema.decimal) = true];
    bytes account = 8 [(schema.address) = true];
  }

  // 下单事件
  message OrderPlaced {
    // order id
    uint64 id = 1;
    uint32 base_token = 2;
    uint32 quote_token = 3;
    PositionMode mode = 4;
    PositionSide side = 5;
    string amount = 6 [(schema.decimal) = true];
    optional string cross_order_frozen = 7 [(schema.decimal) = true];
    optional string isolated_order_frozen = 8 [(schema.decimal) = true];
    bytes account = 9 [(schema.address) = true];
  }

  // 保险基金补贴平仓手续费事件
  message InsuranceExecutedFeeLossCovered {
    // position id
    uint64 id = 1;
    uint32 base_token = 2;
    uint32 quote_token = 3;
    PositionMode mode = 4;
    PositionSide side = 5;
    string amount = 6 [(schema.decimal) = true];
    string wallet = 7 [(schema.decimal) = true];
    bytes account = 8 [(schema.address) = true];
  }

  // 加仓事件
  message PositionIncreased {
    // position id
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    string fee = 7 [(schema.decimal) = true];
    optional string isolated_position_frozen = 8 [(schema.decimal) = true];
    optional string isolated_order_frozen = 9 [(schema.decimal) = true];
    optional string cross_order_frozen = 10 [(schema.decimal) = true];
    string wallet = 11 [(schema.decimal) = true];
  }

  // 减仓事件
  message PositionDecreased {
    // position id
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    string fee = 7 [(schema.decimal) = true];
    // 仅包含平仓盈亏，不包含手续费
    string realized_pnl = 8 [(schema.decimal) = true];
    string wallet = 9 [(schema.decimal) = true];
    optional string isolated_position_frozen = 10 [(schema.decimal) = true];
  }

  // 保险基金补贴PnL事件
  message InsurancePnLLossCovered {
    // position id
    uint64 id = 1;
    uint32 base_token = 2;
    uint32 quote_token = 3;
    PositionMode mode = 4;
    PositionSide side = 5;
    string amount = 6 [(schema.decimal) = true];
    string wallet = 7 [(schema.decimal) = true];
    bytes account = 8 [(schema.address) = true];
  }

  // 仓位保证金增加事件
  message PositionMarginIncreased {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionSide side = 5;
    // 增加的金额，该值为正数
    string amount = 6 [(schema.decimal) = true];
    string isolated_position_frozen = 7 [(schema.decimal) = true];
  }

  // 仓位保证金减少事件
  message PositionMarginDecreased {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionSide side = 5;
    // 减少的金额，该值为负数
    string amount = 6 [(schema.decimal) = true];
    string isolated_position_frozen = 7 [(schema.decimal) = true];
  }

  // 撮合完成后，重新计算需要的订单保证金，释放多冻结的部分保证金
  message OrderFrozenReleased {
    bytes account = 1 [(schema.address) = true];
    uint32 base_token = 2;
    uint32 quote_token = 3;
    PositionMode mode = 4;
    string amount = 5 [(schema.decimal) = true];
    optional string cross_order_frozen = 6 [(schema.decimal) = true];
    optional string isolated_order_frozen = 7 [(schema.decimal) = true];
  }

  // 仓位杠杆变更后，保证金会发生变更
  message PositionLeverageChanged {
    // position id
    optional uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    optional string isolated_position_frozen = 5 [(schema.decimal) = true];
    optional string isolated_order_frozen = 6 [(schema.decimal) = true];
    optional string cross_order_frozen = 7 [(schema.decimal) = true];
  }
}

message TriggerParams {
  TriggerDirection trigger_direction = 1;
  string trigger_price = 2 [(schema.decimal) = true];
  OrderType trigger_order_type = 3;
  string price = 4 [(schema.decimal) = true];
}

message TrailingParams {
  StopType stop_type = 1;
  string activation_price = 2 [(schema.decimal) = true];
  string trailing_base_price = 3 [(schema.decimal) = true];
  TrailingDeltaType trailing_delta_type = 4;
  string trailing_delta = 5 [(schema.decimal) = true];
  // 当追踪订单被激活后的触发价格
  //
  // # 计算规则
  //	1. 当 TriggerDirection 为 TriggerAbove, TrailingDeltaType 为
  // TrailingDeltaTypeDistance 时，TriggerPrice = TrailingBasePrice +
  // TrailingDelta
  //	2. 当 TriggerDirection 为 TriggerAbove, TrailingDeltaType 为
  // TrailingDeltaTypePercentage 时，TriggerPrice = TrailingBasePrice + (1 +
  // TrailingDelta)
  //	3. 当 TriggerDirection 为 TriggerBelow, TrailingDeltaType 为
  // TrailingDeltaTypeDistance 时，TriggerPrice = TrailingBasePrice -
  // TrailingDelta
  //	4. 当 TriggerDirection 为 TriggerBelow, TrailingDeltaType 为
  // TrailingDeltaTypePercentage 时，TriggerPrice = TrailingBasePrice + (1 -
  // TrailingDelta)
  //
  // When the trailing order is activated, the trigger price of the trailing
  // order.
  //
  // # Calculation rules
  //	1. When TriggerDirection is TriggerAbove and TrailingDeltaType is
  // TrailingDeltaTypeDistance, TriggerPrice = TrailingBasePrice + TrailingDelta
  //	2. When TriggerDirection is TriggerAbove and TrailingDeltaType is
  // TrailingDeltaTypePercentage, TriggerPrice = TrailingBasePrice + (1 +
  // TrailingDelta)
  //	3. When TriggerDirection is TriggerBelow and TrailingDeltaType is
  // TrailingDeltaTypeDistance, TriggerPrice = TrailingBasePrice - TrailingDelta
  //	4. When TriggerDirection is TriggerBelow and TrailingDeltaType is
  // TrailingDeltaTypePercentage, TriggerPrice = TrailingBasePrice + (1 -
  // TrailingDelta)
  string trigger_price = 6 [(schema.decimal) = true];
  OrderType trigger_order_type = 7;
}

message L2bookChange {
  repeated L2bookChangeGroupEntry changes = 1;
}

message L2bookChangeGroupEntry {
  uint32 base_token = 1;
  uint32 quote_token = 2;
  repeated L2bookChangeEntry ask_changes = 3;
  repeated L2bookChangeEntry bid_changes = 4;
  optional L2bookChangeEntry ask_1 = 5;
  optional L2bookChangeEntry bid_1 = 6;
}

message L2bookChangeEntry {
  string price = 1 [(schema.decimal) = true];
  string size = 2 [(schema.decimal) = true];
}

message TriggerOrderChange {
  repeated TriggerOrderChangeEntry changes = 3;
}

message TriggerOrderChangeEntry {
  // 当该事件发射时代表订单需要被触发
  message OrderTriggered {
    uint64 id = 1;
    uint32 base_token = 2;
    uint32 quote_token = 3;
    bytes account = 4 [(schema.address) = true];
    TriggerDirection direction = 5;
    // 触发价格
    string price = 6 [(schema.decimal) = true];
    bool tp_triggered = 7;
  }
  // 当该事件发射时代表移动止盈止损的数据需要被更新
  message OrderTrailingBasePriceChanged {
    uint64 id = 1;
    uint32 base_token = 2;
    uint32 quote_token = 3;
    bytes account = 4 [(schema.address) = true];
    // 触发价格
    string price = 5 [(schema.decimal) = true];
    string trailing_base_price = 6 [(schema.decimal) = true];
    string trigger_price = 7 [(schema.decimal) = true];
  }

  oneof change {
    OrderTriggered triggered = 1;
    OrderTrailingBasePriceChanged trailing_base_price_changed = 2;
  }
}

message FundingChange {
  repeated FundingRateChangeEntry changes = 1;
}

message FundingRateChangeEntry {
  uint32 base_token = 1;
  uint32 quote_token = 2;
  string funding_rate = 3 [(schema.decimal) = true];
  google.protobuf.Timestamp update_time = 4;
  uint32 interval_hours = 5;
  string funding_rate_bound = 6 [(schema.decimal) = true];

  bool settled = 7;
  optional string growth_delta = 8 [(schema.decimal) = true];
  optional string long_growth_after = 9 [(schema.decimal) = true];
  optional string short_growth_after = 10 [(schema.decimal) = true];
}

message PriceChange {
  repeated PriceChangeEntry changes = 1;
}

message PriceChangeEntry {
  uint32 base_token = 1;
  uint32 quote_token = 2;
  string index_price = 3 [(schema.decimal) = true];
  string mark_price = 4 [(schema.decimal) = true];
  google.protobuf.Timestamp update_time = 5;
}

message MetadataChange {
  repeated MetadataChangeEntry changes = 1;
}

message MetadataChangeEntry {
  message ChainEnabled {
    uint64 chain_id = 1;
    string chain_name = 2;
  }
  message ChainDisabled {
    uint64 chain_id = 1;
  }
  message TokenMetadataChanged {
    uint32 id = 1;
    string name = 2;
    string symbol = 3;
    uint32 decimals = 4;
    bool deposit_enabled = 5;
  }
  message RiskLimitsRegistered {
    uint32 id = 1;
    repeated RiskLimitMessage risk_limits = 2;
  }
  message SymbolMetadataChanged {
    uint32 base_token = 1;
    uint32 quote_token = 2;
    int64 open_time = 3;
    int64 close_time = 4;
    string tick_size = 5 [(schema.decimal) = true];
    string lot_size = 6 [(schema.decimal) = true];
    string min_size = 7 [(schema.decimal) = true];
    uint32 max_number_of_order_each_match = 8;
    uint32 max_number_of_order_each_account = 9;
    uint32 funding_interval_hours = 10;
    string funding_rate_bound = 11 [(schema.decimal) = true];
    string price_limit_bound = 12
        [(schema.decimal) = true];  // 限价单价格限制比例
    uint32 default_leverage = 13;
    uint32 risk_limits_id = 14;
  }
  message FeeTierChanged {
    repeated FeeTierMessage fee_tiers = 1;
  }
  message AgentApproved {
    bytes account = 1 [(schema.address) = true];
    bytes agent = 2 [(schema.address) = true];
    string name = 3;
    google.protobuf.Timestamp expired_time = 4;
  }
  message AgentRevoked {
    bytes account = 1 [(schema.address) = true];
    string name = 2;
  }
  message AgentExpired {
    bytes account = 1 [(schema.address) = true];
    repeated string names = 2;
  }
  message AccountFeeTierChanged {
    bytes account = 1 [(schema.address) = true];
    FeeTierMessage fee_tier = 2;
  }
  oneof change {
    ChainEnabled chain_enabled = 1;
    ChainDisabled chain_disabled = 2;
    TokenMetadataChanged token_metadata_changed = 3;
    RiskLimitsRegistered risk_limits_registered = 4;
    SymbolMetadataChanged symbol_metadata_changed = 5;
    FeeTierChanged fee_tier_changed = 6;
    AgentApproved agent_approved = 7;
    AgentRevoked agent_revoked = 8;
    AgentExpired agent_expired = 9;
    AccountFeeTierChanged account_fee_tier_changed = 10;
  }
}

message OrderChange {
  repeated OrderChangeEntry changes = 1;
}

message OrderChangeEntry {
  message TrailingParams {
    StopType stop_type = 1;
    optional string activation_price = 2 [(schema.decimal) = true];
    optional string trailing_base_price = 3 [(schema.decimal) = true];
    TrailingDeltaType trailing_delta_type = 4;
    string trailing_delta = 5 [(schema.decimal) = true];
    optional string trigger_price = 6 [(schema.decimal) = true];
    OrderType trigger_order_type = 7;
    OrderTimeInForce time_in_force = 8;
    // When TriggerOrderType is Limit, the price of the limit order
    optional string price = 9 [(schema.decimal) = true];
    // 当size为0，则强制reduce_only为true（即只能为只减仓）。
    // 当主订单类型为Limit或Market，则止盈止损的订单数量为成交数量。
    // 当主订单类型为Trigger，则订单数量为当前的持仓。
    // 当主订单类型为TakeProfitStopLoss，则订单数量为当前的持仓。
    // 当主订单类型为Trailing，则订单数量为当前的持仓。
    optional string size = 10 [(schema.decimal) = true];
    bool reduce_only = 11;
    SelfTradePreventionMode stp_mode = 12;
  }
  message OrderPlaced {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    OrderType type = 7;
    OrderTimeInForce time_in_force = 8;
    optional string price = 9 [(schema.decimal) = true];
    optional string size = 10 [(schema.decimal) = true];
    bool reduce_only = 11;
    optional uint64 position_id = 12;
    string taker_fee_rate = 13 [(schema.decimal) = true];
    string make_fee_rate = 14 [(schema.decimal) = true];

    optional TriggerParamsMessage trigger = 15;
    optional TriggerParamsMessage tp = 16;
    optional TriggerParamsMessage sl = 17;
    bool tp_triggered = 18;
    optional TrailingParams trailing = 19;
    SelfTradePreventionMode stp_mode = 20;
    optional bytes client_order_id = 21;
  }
  message OrderCancelled {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    OrderType type = 7;
    // 取消的size
    optional string size = 8 [(schema.decimal) = true];
    optional bytes client_order_id = 9;
  }
  message OrderExpired {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    OrderType type = 7;
    // 过期的size
    optional string size = 8 [(schema.decimal) = true];
    optional bytes client_order_id = 9;
  }
  message OrderExecuted {
    uint32 base_token = 1;
    uint32 quote_token = 2;
    uint64 taker_order_id = 3;
    bytes taker_account = 4 [(schema.address) = true];
    PositionMode taker_mode = 5;
    PositionSide taker_side = 6;

    string price = 7 [(schema.decimal) = true];
    string size = 8 [(schema.decimal) = true];

    // taker支付的手续费，总是小于等于0
    string taker_fee = 9 [(schema.decimal) = true];
    bool taker_order_filled = 10;

    // fields for maker order

    uint64 maker_order_id = 11;
    bytes maker_account = 12 [(schema.address) = true];
    PositionMode maker_mode = 13;
    // positive value means maker receive fee, negative value means maker pay
    // fee
    string maker_fee = 14 [(schema.decimal) = true];
    bool maker_order_filled = 15;
  }
  message OrderTriggerFailed {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    OrderType type = 7;
    // 失败原因
    ErrorCode error_code = 8;
    optional bytes client_order_id = 9;
  }
  message OrderTriggerSucceeded {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    OrderType type = 7;
    uint64 triggered_order_id = 8;
    optional bytes client_order_id = 9;
  }
  message OrderAmended {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    OrderType type = 7;
    string price_after = 8 [(schema.decimal) = true];
    string size_after = 9 [(schema.decimal) = true];
    optional bytes client_order_id = 10;
  }
  message OrderFeeRateChanged {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    OrderType type = 7;
    string taker_fee_rate = 8 [(schema.decimal) = true];
    string maker_fee_rate = 9 [(schema.decimal) = true];
    optional bytes client_order_id = 10;
  }
  oneof change {
    OrderPlaced placed = 1;
    OrderCancelled cancelled = 2;
    OrderExpired expired = 3;
    OrderExecuted executed = 4;
    OrderTriggerFailed trigger_failed = 5;
    OrderTriggerSucceeded trigger_succeeded = 6;
    OrderAmended amended = 7;
    OrderFeeRateChanged fee_rate_changed = 8;
  }
}

message PositionChange {
  repeated PositionChangeEntry changes = 1;
}

message PositionChangeEntry {
  message PositionIncreased {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    string filled_size = 7 [(schema.decimal) = true];
    string size_after = 8 [(schema.decimal) = true];
    string filled_price = 9 [(schema.decimal) = true];
    string entry_price_after = 10 [(schema.decimal) = true];
    // 正数表示收入，负数表示支出
    string fee = 11 [(schema.decimal) = true];
    string realized_pnl_after = 12 [(schema.decimal) = true];
    optional string isolated_margin_after = 13 [(schema.decimal) = true];
    string taker_fee_rate = 14 [(schema.decimal) = true];
    uint32 risk_limits_id = 15;
    string funding_growth = 16 [(schema.decimal) = true];
  }
  message PositionDecreased {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    string filled_size = 7 [(schema.decimal) = true];
    string size_after = 8 [(schema.decimal) = true];
    string filled_price = 9 [(schema.decimal) = true];
    // 正数表示收入，负数表示支出
    string fee = 10 [(schema.decimal) = true];
    // 平仓盈亏（不包含手续费）
    string realized_pnl = 11 [(schema.decimal) = true];
    string realized_pnl_after = 12 [(schema.decimal) = true];
    optional string isolated_margin_after = 13 [(schema.decimal) = true];
  }
  message PositionFundingSettled {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionMode mode = 5;
    PositionSide side = 6;
    string funding_growth = 10 [(schema.decimal) = true];
    string funding_fee = 11 [(schema.decimal) = true];
  }
  message PositionModeChanged {
    bytes account = 1 [(schema.address) = true];
    uint32 base_token = 2;
    uint32 quote_token = 3;
    PositionMode mode = 4;
    uint32 isolated_leverage = 5;
    uint32 cross_leverage = 6;
  }
  message PositionMarginIncreased {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionSide side = 5;
    // 增加的金额，该值为正数
    string amount = 6 [(schema.decimal) = true];
    string isolated_margin_after = 7 [(schema.decimal) = true];
  }
  message PositionMarginDecreased {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    PositionSide side = 5;
    // 减少的金额，该值为负数
    string amount = 6 [(schema.decimal) = true];
    string isolated_margin_after = 7 [(schema.decimal) = true];
  }
  message PositionLeverageChanged {
    uint64 id = 1;
    bytes account = 2 [(schema.address) = true];
    uint32 base_token = 3;
    uint32 quote_token = 4;
    // 正数表示逐仓保证金增加，负数表示逐仓保证金减少
    string amount = 5 [(schema.decimal) = true];
    string isolated_margin_after = 6 [(schema.decimal) = true];
  }

  oneof change {
    PositionIncreased increased = 1;
    PositionDecreased decreased = 2;
    PositionFundingSettled funding_settled = 3;
    PositionModeChanged mode_changed = 4;
    PositionMarginIncreased margin_increased = 5;
    PositionMarginDecreased margin_decreased = 6;
    PositionLeverageChanged leverage_changed = 7;
  }
}
