# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/snapshot/balances.snap.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'schema/snapshot/balances.snap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#schema/snapshot/balances.snap.proto\x12\x15share.schema.snapshot\"\xb9\x01\n\x0b\x42\x61lancesRow\x12\x12\n\naccount_id\x18\x01 \x01(\x0c\x12\x0e\n\x06wallet\x18\x02 \x01(\t\x12 \n\x18isolated_position_frozen\x18\x03 \x01(\t\x12\x1d\n\x15isolated_order_frozen\x18\x04 \x01(\t\x12\x1a\n\x12\x63ross_order_frozen\x18\x05 \x01(\t\x12\x13\n\x0b\x65ntry_price\x18\x06 \x01(\t\x12\x14\n\x0crealized_pnl\x18\x07 \x01(\tB4Z2github.com/exc-works/caishen/share/schema/snapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.snapshot.balances.snap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/exc-works/caishen/share/schema/snapshot'
  _globals['_BALANCESROW']._serialized_start=63
  _globals['_BALANCESROW']._serialized_end=248
# @@protoc_insertion_point(module_scope)
