# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin/symbol.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'admin/symbol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x64min/symbol.proto\x12\x05token\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"\x14\n\x12SyncSymbolsRequest\"\x15\n\x13SyncSymbolsResponse\"\x16\n\x14ResyncSymbolsRequest\"\x17\n\x15ResyncSymbolsResponse2\xd6\x01\n\x06Symbol\x12\x61\n\x0bSyncSymbols\x12\x19.token.SyncSymbolsRequest\x1a\x1a.token.SyncSymbolsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/symbols/sync:\x01*\x12i\n\rResyncSymbols\x12\x1b.token.ResyncSymbolsRequest\x1a\x1c.token.ResyncSymbolsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x12/v1/symbols/resync:\x01*B*Z(github.com/exc-works/caishen/admin/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin.symbol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/exc-works/caishen/admin/types'
  _globals['_SYMBOL'].methods_by_name['SyncSymbols']._loaded_options = None
  _globals['_SYMBOL'].methods_by_name['SyncSymbols']._serialized_options = b'\202\323\344\223\002\025\"\020/v1/symbols/sync:\001*'
  _globals['_SYMBOL'].methods_by_name['ResyncSymbols']._loaded_options = None
  _globals['_SYMBOL'].methods_by_name['ResyncSymbols']._serialized_options = b'\202\323\344\223\002\027\"\022/v1/symbols/resync:\001*'
  _globals['_SYNCSYMBOLSREQUEST']._serialized_start=81
  _globals['_SYNCSYMBOLSREQUEST']._serialized_end=101
  _globals['_SYNCSYMBOLSRESPONSE']._serialized_start=103
  _globals['_SYNCSYMBOLSRESPONSE']._serialized_end=124
  _globals['_RESYNCSYMBOLSREQUEST']._serialized_start=126
  _globals['_RESYNCSYMBOLSREQUEST']._serialized_end=148
  _globals['_RESYNCSYMBOLSRESPONSE']._serialized_start=150
  _globals['_RESYNCSYMBOLSRESPONSE']._serialized_end=173
  _globals['_SYMBOL']._serialized_start=176
  _globals['_SYMBOL']._serialized_end=390
# @@protoc_insertion_point(module_scope)
