# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/agent.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'schema/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema import extensions_pb2 as schema_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12schema/agent.proto\x12\x0cshare.schema\x1a\x17schema/extensions.proto\"N\n\x13\x41pproveAgentMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x05\x61gent\x18\x02 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12\x14\n\x0c\x65xpired_time\x18\x03 \x01(\x03\x42+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_APPROVEAGENTMESSAGE'].fields_by_name['agent']._loaded_options = None
  _globals['_APPROVEAGENTMESSAGE'].fields_by_name['agent']._serialized_options = b'\220\265\030\001'
  _globals['_APPROVEAGENTMESSAGE']._serialized_start=61
  _globals['_APPROVEAGENTMESSAGE']._serialized_end=139
# @@protoc_insertion_point(module_scope)
