# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/chain.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'schema/chain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema import extensions_pb2 as schema_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12schema/chain.proto\x12\x0cshare.schema\x1a\x17schema/extensions.proto\":\n\x12\x45nableChainMessage\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\x04\x12\x12\n\nchain_name\x18\x02 \x01(\t\"\'\n\x13\x44isableChainMessage\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\x04\"P\n\x11ProposerSetConfig\x12\x11\n\tproposers\x18\x01 \x03(\x0c\x12\x0f\n\x07weights\x18\x02 \x03(\t\x12\x17\n\tthreshold\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01\"\x81\x01\n\x1eUpdateDomainProposerSetMessage\x12.\n\x06\x64omain\x18\x01 \x01(\x0e\x32\x1e.share.schema.PermissionDomain\x12/\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1f.share.schema.ProposerSetConfig*\xb1\x02\n\x10PermissionDomain\x12\x0c\n\x08PROPOSER\x10\x00\x12\t\n\x05\x43HAIN\x10\x01\x12\x14\n\x10\x41\x43\x43OUNT_FEE_TIER\x10\x02\x12\x0f\n\x0bINDEX_PRICE\x10\x03\x12\x10\n\x0c\x46UNDING_RATE\x10\x04\x12\x14\n\x10\x44\x45POSIT_WITHDRAW\x10\x05\x12\x15\n\x11\x41UTO_DELEVERAGING\x10\x06\x12\x15\n\x11\x43ONDITIONAL_ORDER\x10\x07\x12\x12\n\x0eSTRATEGY_ORDER\x10\x08\x12\x12\n\x0eINSURANCE_FUND\x10\t\x12\x07\n\x03\x46\x45\x45\x10\n\x12\x0e\n\nPREDICTION\x10\x0b\x12\x10\n\x0cPLACEHOLDER4\x10\x0c\x12\x10\n\x0cPLACEHOLDER5\x10\r\x12\x10\n\x0cPLACEHOLDER6\x10\x0e\x12\x10\n\x0cPLACEHOLDER7\x10\x0f\x42+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.chain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_PROPOSERSETCONFIG'].fields_by_name['threshold']._loaded_options = None
  _globals['_PROPOSERSETCONFIG'].fields_by_name['threshold']._serialized_options = b'\210\265\030\001'
  _globals['_PERMISSIONDOMAIN']._serialized_start=377
  _globals['_PERMISSIONDOMAIN']._serialized_end=682
  _globals['_ENABLECHAINMESSAGE']._serialized_start=61
  _globals['_ENABLECHAINMESSAGE']._serialized_end=119
  _globals['_DISABLECHAINMESSAGE']._serialized_start=121
  _globals['_DISABLECHAINMESSAGE']._serialized_end=160
  _globals['_PROPOSERSETCONFIG']._serialized_start=162
  _globals['_PROPOSERSETCONFIG']._serialized_end=242
  _globals['_UPDATEDOMAINPROPOSERSETMESSAGE']._serialized_start=245
  _globals['_UPDATEDOMAINPROPOSERSETMESSAGE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
