# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/fee_tier.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'schema/fee_tier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema import base_pb2 as schema_dot_base__pb2
from schema import extensions_pb2 as schema_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15schema/fee_tier.proto\x12\x0cshare.schema\x1a\x11schema/base.proto\x1a\x17schema/extensions.proto\"H\n\x0e\x46\x65\x65TierMessage\x12\x0c\n\x04tier\x18\x01 \x01(\r\x12\x13\n\x05taker\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01\x12\x13\n\x05maker\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01\"~\n\x16RegisterFeeTierMessage\x12\x33\n\x0etrading_domain\x18\x01 \x01(\x0e\x32\x1b.share.schema.TradingDomain\x12/\n\tfee_tiers\x18\x02 \x03(\x0b\x32\x1c.share.schema.FeeTierMessage\"<\n\x15\x41\x63\x63ountFeeTierMessage\x12\x15\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12\x0c\n\x04tier\x18\x02 \x01(\r\"_\n\x1dRegisterAccountFeeTierMessage\x12>\n\x11\x61\x63\x63ount_fee_tiers\x18\x02 \x03(\x0b\x32#.share.schema.AccountFeeTierMessageB+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.fee_tier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_FEETIERMESSAGE'].fields_by_name['taker']._loaded_options = None
  _globals['_FEETIERMESSAGE'].fields_by_name['taker']._serialized_options = b'\210\265\030\001'
  _globals['_FEETIERMESSAGE'].fields_by_name['maker']._loaded_options = None
  _globals['_FEETIERMESSAGE'].fields_by_name['maker']._serialized_options = b'\210\265\030\001'
  _globals['_ACCOUNTFEETIERMESSAGE'].fields_by_name['account']._loaded_options = None
  _globals['_ACCOUNTFEETIERMESSAGE'].fields_by_name['account']._serialized_options = b'\220\265\030\001'
  _globals['_FEETIERMESSAGE']._serialized_start=83
  _globals['_FEETIERMESSAGE']._serialized_end=155
  _globals['_REGISTERFEETIERMESSAGE']._serialized_start=157
  _globals['_REGISTERFEETIERMESSAGE']._serialized_end=283
  _globals['_ACCOUNTFEETIERMESSAGE']._serialized_start=285
  _globals['_ACCOUNTFEETIERMESSAGE']._serialized_end=345
  _globals['_REGISTERACCOUNTFEETIERMESSAGE']._serialized_start=347
  _globals['_REGISTERACCOUNTFEETIERMESSAGE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
