# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/funding.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'schema/funding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema import extensions_pb2 as schema_dot_extensions__pb2
from schema import order_pb2 as schema_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14schema/funding.proto\x12\x0cshare.schema\x1a\x17schema/extensions.proto\x1a\x12schema/order.proto\"O\n\x18UpdateFundingRateMessage\x12\x33\n\x0b\x62\x61se_quotes\x18\x01 \x03(\x0b\x32\x1e.share.schema.BaseQuoteMessage\";\n\x10\x42\x61seQuoteMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\"Z\n\x17SettleFundingFeeMessage\x12(\n\x04mode\x18\x01 \x01(\x0e\x32\x1a.share.schema.PositionMode\x12\x15\n\x07\x61\x63\x63ount\x18\x02 \x01(\x0c\x42\x04\x90\xb5\x18\x01\"~\n\x1dSettleBatchFundingFeesMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12\x34\n\x05\x62\x61tch\x18\x03 \x03(\x0b\x32%.share.schema.SettleFundingFeeMessageB+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.funding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_SETTLEFUNDINGFEEMESSAGE'].fields_by_name['account']._loaded_options = None
  _globals['_SETTLEFUNDINGFEEMESSAGE'].fields_by_name['account']._serialized_options = b'\220\265\030\001'
  _globals['_UPDATEFUNDINGRATEMESSAGE']._serialized_start=83
  _globals['_UPDATEFUNDINGRATEMESSAGE']._serialized_end=162
  _globals['_BASEQUOTEMESSAGE']._serialized_start=164
  _globals['_BASEQUOTEMESSAGE']._serialized_end=223
  _globals['_SETTLEFUNDINGFEEMESSAGE']._serialized_start=225
  _globals['_SETTLEFUNDINGFEEMESSAGE']._serialized_end=315
  _globals['_SETTLEBATCHFUNDINGFEESMESSAGE']._serialized_start=317
  _globals['_SETTLEBATCHFUNDINGFEESMESSAGE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
