# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/genesis.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'schema/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema import chain_pb2 as schema_dot_chain__pb2
from schema import token_pb2 as schema_dot_token__pb2
from schema import symbol_pb2 as schema_dot_symbol__pb2
from schema import fee_tier_pb2 as schema_dot_fee__tier__pb2
from schema import prediction_pb2 as schema_dot_prediction__pb2
from schema import vault_pb2 as schema_dot_vault__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14schema/genesis.proto\x12\x0cshare.schema\x1a\x12schema/chain.proto\x1a\x12schema/token.proto\x1a\x13schema/symbol.proto\x1a\x15schema/fee_tier.proto\x1a\x17schema/prediction.proto\x1a\x12schema/vault.proto\"\xf0\x05\n\x0eGenesisMessage\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\x04\x12\x12\n\nchain_name\x18\x02 \x01(\t\x12H\n\x12permission_configs\x18\x03 \x03(\x0b\x32,.share.schema.UpdateDomainProposerSetMessage\x12\x38\n\x0e\x65nabled_chains\x18\x04 \x03(\x0b\x32 .share.schema.EnableChainMessage\x12=\n\x11registered_tokens\x18\x05 \x03(\x0b\x32\".share.schema.RegisterTokenMessage\x12]\n#registered_deposit_withdraw_configs\x18\x06 \x03(\x0b\x32\x30.share.schema.UpdateDepositWithdrawConfigMessage\x12G\n\x16registered_risk_limits\x18\x07 \x03(\x0b\x32\'.share.schema.RegisterRiskLimitsMessage\x12?\n\x12registered_symbols\x18\x08 \x03(\x0b\x32#.share.schema.RegisterSymbolMessage\x12\x42\n\x14registered_fee_tiers\x18\t \x03(\x0b\x32$.share.schema.RegisterFeeTierMessage\x12H\n\x17registered_spot_symbols\x18\n \x03(\x0b\x32\'.share.schema.RegisterSpotSymbolMessage\x12\x46\n\x11prediction_config\x18\x0b \x01(\x0b\x32+.share.schema.PredictionUpdateConfigMessage\x12\x36\n\x0cvault_config\x18\x0c \x01(\x0b\x32 .share.schema.VaultConfigMessageB+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_GENESISMESSAGE']._serialized_start=168
  _globals['_GENESISMESSAGE']._serialized_end=920
# @@protoc_insertion_point(module_scope)
