# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/multisig.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'schema/multisig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15schema/multisig.proto\x12\x0cshare.schema\">\n\x18\x43onvertToMultiSigMessage\x12\x11\n\tthreshold\x18\x01 \x01(\r\x12\x0f\n\x07signers\x18\x02 \x03(\x0c\"A\n\x1bUpdateMultiSigConfigMessage\x12\x11\n\tthreshold\x18\x01 \x01(\r\x12\x0f\n\x07signers\x18\x02 \x03(\x0c\"\x19\n\x17\x43onvertToRegularMessageB+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.multisig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_CONVERTTOMULTISIGMESSAGE']._serialized_start=39
  _globals['_CONVERTTOMULTISIGMESSAGE']._serialized_end=101
  _globals['_UPDATEMULTISIGCONFIGMESSAGE']._serialized_start=103
  _globals['_UPDATEMULTISIGCONFIGMESSAGE']._serialized_end=168
  _globals['_CONVERTTOREGULARMESSAGE']._serialized_start=170
  _globals['_CONVERTTOREGULARMESSAGE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
