# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/position.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'schema/position.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema import extensions_pb2 as schema_dot_extensions__pb2
from schema import order_pb2 as schema_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15schema/position.proto\x12\x0cshare.schema\x1a\x17schema/extensions.proto\x1a\x12schema/order.proto\"k\n\x16SetPositionModeMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12(\n\x04mode\x18\x03 \x01(\x0e\x32\x1a.share.schema.PositionMode\"W\n\x1aSetPositionLeverageMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12\x10\n\x08leverage\x18\x03 \x01(\r\"V\n\x15IncreaseMarginMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12\x14\n\x06\x61mount\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01\"V\n\x15\x44\x65\x63reaseMarginMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12\x14\n\x06\x61mount\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01\x42+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.position_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_INCREASEMARGINMESSAGE'].fields_by_name['amount']._loaded_options = None
  _globals['_INCREASEMARGINMESSAGE'].fields_by_name['amount']._serialized_options = b'\210\265\030\001'
  _globals['_DECREASEMARGINMESSAGE'].fields_by_name['amount']._loaded_options = None
  _globals['_DECREASEMARGINMESSAGE'].fields_by_name['amount']._serialized_options = b'\210\265\030\001'
  _globals['_SETPOSITIONMODEMESSAGE']._serialized_start=84
  _globals['_SETPOSITIONMODEMESSAGE']._serialized_end=191
  _globals['_SETPOSITIONLEVERAGEMESSAGE']._serialized_start=193
  _globals['_SETPOSITIONLEVERAGEMESSAGE']._serialized_end=280
  _globals['_INCREASEMARGINMESSAGE']._serialized_start=282
  _globals['_INCREASEMARGINMESSAGE']._serialized_end=368
  _globals['_DECREASEMARGINMESSAGE']._serialized_start=370
  _globals['_DECREASEMARGINMESSAGE']._serialized_end=456
# @@protoc_insertion_point(module_scope)
