# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/position.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'schema/position.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hummingbot.connector.derivative.caishen_perpetual.deepproto.schema import extensions_pb2 as schema_dot_extensions__pb2
from hummingbot.connector.derivative.caishen_perpetual.deepproto.schema import order_pb2 as schema_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15schema/position.proto\x12\x0cshare.schema\x1a\x17schema/extensions.proto\x1a\x12schema/order.proto\"k\n\x16SetPositionModeMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12(\n\x04mode\x18\x03 \x01(\x0e\x32\x1a.share.schema.PositionMode\"W\n\x1aSetPositionLeverageMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12\x10\n\x08leverage\x18\x03 \x01(\r\"V\n\x15IncreaseMarginMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12\x14\n\x06\x61mount\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01\"V\n\x15\x44\x65\x63reaseMarginMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12\x14\n\x06\x61mount\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01\"\xb0\x01\n\x1b\x45nterLiquidationModeMessage\x12\x15\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12(\n\x04mode\x18\x02 \x01(\x0e\x32\x1a.share.schema.PositionMode\x12\x17\n\nbase_token\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0bquote_token\x18\x04 \x01(\rH\x01\x88\x01\x01\x42\r\n\x0b_base_tokenB\x0e\n\x0c_quote_token\"\xaf\x01\n\x1a\x45xitLiquidationModeMessage\x12\x15\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12(\n\x04mode\x18\x02 \x01(\x0e\x32\x1a.share.schema.PositionMode\x12\x17\n\nbase_token\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0bquote_token\x18\x04 \x01(\rH\x01\x88\x01\x01\x42\r\n\x0b_base_tokenB\x0e\n\x0c_quote_token\"\xad\x01\n\x18LiquidatePositionMessage\x12\x15\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12(\n\x04mode\x18\x02 \x01(\x0e\x32\x1a.share.schema.PositionMode\x12\x17\n\nbase_token\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0bquote_token\x18\x04 \x01(\rH\x01\x88\x01\x01\x42\r\n\x0b_base_tokenB\x0e\n\x0c_quote_tokenB+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.position_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_INCREASEMARGINMESSAGE'].fields_by_name['amount']._loaded_options = None
  _globals['_INCREASEMARGINMESSAGE'].fields_by_name['amount']._serialized_options = b'\210\265\030\001'
  _globals['_DECREASEMARGINMESSAGE'].fields_by_name['amount']._loaded_options = None
  _globals['_DECREASEMARGINMESSAGE'].fields_by_name['amount']._serialized_options = b'\210\265\030\001'
  _globals['_ENTERLIQUIDATIONMODEMESSAGE'].fields_by_name['account']._loaded_options = None
  _globals['_ENTERLIQUIDATIONMODEMESSAGE'].fields_by_name['account']._serialized_options = b'\220\265\030\001'
  _globals['_EXITLIQUIDATIONMODEMESSAGE'].fields_by_name['account']._loaded_options = None
  _globals['_EXITLIQUIDATIONMODEMESSAGE'].fields_by_name['account']._serialized_options = b'\220\265\030\001'
  _globals['_LIQUIDATEPOSITIONMESSAGE'].fields_by_name['account']._loaded_options = None
  _globals['_LIQUIDATEPOSITIONMESSAGE'].fields_by_name['account']._serialized_options = b'\220\265\030\001'
  _globals['_SETPOSITIONMODEMESSAGE']._serialized_start=84
  _globals['_SETPOSITIONMODEMESSAGE']._serialized_end=191
  _globals['_SETPOSITIONLEVERAGEMESSAGE']._serialized_start=193
  _globals['_SETPOSITIONLEVERAGEMESSAGE']._serialized_end=280
  _globals['_INCREASEMARGINMESSAGE']._serialized_start=282
  _globals['_INCREASEMARGINMESSAGE']._serialized_end=368
  _globals['_DECREASEMARGINMESSAGE']._serialized_start=370
  _globals['_DECREASEMARGINMESSAGE']._serialized_end=456
  _globals['_ENTERLIQUIDATIONMODEMESSAGE']._serialized_start=459
  _globals['_ENTERLIQUIDATIONMODEMESSAGE']._serialized_end=635
  _globals['_EXITLIQUIDATIONMODEMESSAGE']._serialized_start=638
  _globals['_EXITLIQUIDATIONMODEMESSAGE']._serialized_end=813
  _globals['_LIQUIDATEPOSITIONMESSAGE']._serialized_start=816
  _globals['_LIQUIDATEPOSITIONMESSAGE']._serialized_end=989
# @@protoc_insertion_point(module_scope)
