# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/price.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'schema/price.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema import extensions_pb2 as schema_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12schema/price.proto\x12\x0cshare.schema\x1a\x17schema/extensions.proto\"^\n\x17UpdateIndexPriceMessage\x12\x30\n\x06prices\x18\x01 \x03(\x0b\x32 .share.schema.SymbolPriceMessage\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"X\n\x12SymbolPriceMessage\x12\x12\n\nbase_token\x18\x01 \x01(\r\x12\x13\n\x0bquote_token\x18\x02 \x01(\r\x12\x19\n\x0bindex_price\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01\x42+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.price_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_SYMBOLPRICEMESSAGE'].fields_by_name['index_price']._loaded_options = None
  _globals['_SYMBOLPRICEMESSAGE'].fields_by_name['index_price']._serialized_options = b'\210\265\030\001'
  _globals['_UPDATEINDEXPRICEMESSAGE']._serialized_start=61
  _globals['_UPDATEINDEXPRICEMESSAGE']._serialized_end=155
  _globals['_SYMBOLPRICEMESSAGE']._serialized_start=157
  _globals['_SYMBOLPRICEMESSAGE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
