# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/subaccount.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'schema/subaccount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17schema/subaccount.proto\x12\x0cshare.schema\"S\n\x17\x43reateSubaccountMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.share.schema.SubaccountType*<\n\x0eSubaccountType\x12\x10\n\x0cUSER_CREATED\x10\x00\x12\x08\n\x04GRID\x10\x01\x12\x0e\n\nMARTINGALE\x10\x02\x42+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.subaccount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_SUBACCOUNTTYPE']._serialized_start=126
  _globals['_SUBACCOUNTTYPE']._serialized_end=186
  _globals['_CREATESUBACCOUNTMESSAGE']._serialized_start=41
  _globals['_CREATESUBACCOUNTMESSAGE']._serialized_end=124
# @@protoc_insertion_point(module_scope)
