# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/token.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'schema/token.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hummingbot.connector.derivative.caishen_perpetual.deepproto.schema import extensions_pb2 as schema_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12schema/token.proto\x12\x0cshare.schema\x1a\x17schema/extensions.proto\"k\n\x14RegisterTokenMessage\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65\x63imals\x18\x04 \x01(\r\x12\x17\n\x0f\x64\x65posit_enabled\x18\x05 \x01(\x08\"\x9c\x01\n\x13\x44\x65positTokenMessage\x12\x10\n\x08token_id\x18\x01 \x01(\r\x12\x14\n\x06\x61mount\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\r\x12\x14\n\x0c\x64\x65posit_hash\x18\x04 \x01(\x0c\x12\x16\n\x08receiver\x18\x05 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12\x1d\n\x0fidempotency_key\x18\x06 \x01(\x0c\x42\x04\x98\xb5\x18\x01\"h\n\x14WithdrawTokenMessage\x12\x10\n\x08token_id\x18\x01 \x01(\r\x12\x14\n\x06\x61mount\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\r\x12\x16\n\x08receiver\x18\x04 \x01(\x0c\x42\x04\x90\xb5\x18\x01\"E\n\x1b\x43onfirmWithdrawTokenMessage\x12\x12\n\npending_id\x18\x01 \x01(\x04\x12\x12\n\x04hash\x18\x02 \x01(\x0c\x42\x04\x98\xb5\x18\x01\"@\n\x1aRejectWithdrawTokenMessage\x12\x12\n\npending_id\x18\x01 \x01(\x04\x12\x0e\n\x06reason\x18\x02 \x01(\t\"V\n\x14TransferTokenMessage\x12\x10\n\x08token_id\x18\x01 \x01(\r\x12\x14\n\x06\x61mount\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01\x12\x16\n\x08receiver\x18\x03 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x42+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.token_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_DEPOSITTOKENMESSAGE'].fields_by_name['amount']._loaded_options = None
  _globals['_DEPOSITTOKENMESSAGE'].fields_by_name['amount']._serialized_options = b'\210\265\030\001'
  _globals['_DEPOSITTOKENMESSAGE'].fields_by_name['receiver']._loaded_options = None
  _globals['_DEPOSITTOKENMESSAGE'].fields_by_name['receiver']._serialized_options = b'\220\265\030\001'
  _globals['_DEPOSITTOKENMESSAGE'].fields_by_name['idempotency_key']._loaded_options = None
  _globals['_DEPOSITTOKENMESSAGE'].fields_by_name['idempotency_key']._serialized_options = b'\230\265\030\001'
  _globals['_WITHDRAWTOKENMESSAGE'].fields_by_name['amount']._loaded_options = None
  _globals['_WITHDRAWTOKENMESSAGE'].fields_by_name['amount']._serialized_options = b'\210\265\030\001'
  _globals['_WITHDRAWTOKENMESSAGE'].fields_by_name['receiver']._loaded_options = None
  _globals['_WITHDRAWTOKENMESSAGE'].fields_by_name['receiver']._serialized_options = b'\220\265\030\001'
  _globals['_CONFIRMWITHDRAWTOKENMESSAGE'].fields_by_name['hash']._loaded_options = None
  _globals['_CONFIRMWITHDRAWTOKENMESSAGE'].fields_by_name['hash']._serialized_options = b'\230\265\030\001'
  _globals['_TRANSFERTOKENMESSAGE'].fields_by_name['amount']._loaded_options = None
  _globals['_TRANSFERTOKENMESSAGE'].fields_by_name['amount']._serialized_options = b'\210\265\030\001'
  _globals['_TRANSFERTOKENMESSAGE'].fields_by_name['receiver']._loaded_options = None
  _globals['_TRANSFERTOKENMESSAGE'].fields_by_name['receiver']._serialized_options = b'\220\265\030\001'
  _globals['_REGISTERTOKENMESSAGE']._serialized_start=61
  _globals['_REGISTERTOKENMESSAGE']._serialized_end=168
  _globals['_DEPOSITTOKENMESSAGE']._serialized_start=171
  _globals['_DEPOSITTOKENMESSAGE']._serialized_end=327
  _globals['_WITHDRAWTOKENMESSAGE']._serialized_start=329
  _globals['_WITHDRAWTOKENMESSAGE']._serialized_end=433
  _globals['_CONFIRMWITHDRAWTOKENMESSAGE']._serialized_start=435
  _globals['_CONFIRMWITHDRAWTOKENMESSAGE']._serialized_end=504
  _globals['_REJECTWITHDRAWTOKENMESSAGE']._serialized_start=506
  _globals['_REJECTWITHDRAWTOKENMESSAGE']._serialized_end=570
  _globals['_TRANSFERTOKENMESSAGE']._serialized_start=572
  _globals['_TRANSFERTOKENMESSAGE']._serialized_end=658
# @@protoc_insertion_point(module_scope)
