# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/vault.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'schema/vault.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema import extensions_pb2 as schema_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12schema/vault.proto\x12\x0cshare.schema\x1a\x17schema/extensions.proto\"8\n\x12VaultConfigMessage\x12\"\n\x1awithdraw_min_hold_duration\x18\x01 \x01(\x03\"U\n\x12\x43reateVaultMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1c\n\x0e\x64\x65posit_amount\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01\"P\n\x13VaultDepositMessage\x12\x1b\n\rvault_account\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12\x1c\n\x0e\x64\x65posit_amount\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01\"N\n\x16SetVaultDepositMessage\x12\x1b\n\rvault_account\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12\x17\n\x0f\x64\x65posit_enabled\x18\x02 \x01(\x08\"a\n\"SetVaultAutoCloseOnWithdrawMessage\x12\x1b\n\rvault_account\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12\x1e\n\x16\x61uto_close_on_withdraw\x18\x02 \x01(\x08\"7\n\x18PrepareCloseVaultMessage\x12\x1b\n\rvault_account\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\"7\n\x18\x45xecuteCloseVaultMessage\x12\x1b\n\rvault_account\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\"3\n\x14MaintainVaultMessage\x12\x1b\n\rvault_account\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\"R\n\x14VaultWithdrawMessage\x12\x1b\n\rvault_account\x18\x01 \x01(\x0c\x42\x04\x90\xb5\x18\x01\x12\x1d\n\x0fwithdraw_amount\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01*w\n\x0bVaultStatus\x12\x17\n\x13VAULT_STATUS_NORMAL\x10\x00\x12\x18\n\x14VAULT_STATUS_CLOSING\x10\x01\x12\x17\n\x13VAULT_STATUS_CLOSED\x10\x02\x12\x1c\n\x18VAULT_STATUS_MAINTAINING\x10\x03\x42+Z)github.com/exc-works/caishen/share/schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.vault_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/exc-works/caishen/share/schema'
  _globals['_CREATEVAULTMESSAGE'].fields_by_name['deposit_amount']._loaded_options = None
  _globals['_CREATEVAULTMESSAGE'].fields_by_name['deposit_amount']._serialized_options = b'\210\265\030\001'
  _globals['_VAULTDEPOSITMESSAGE'].fields_by_name['vault_account']._loaded_options = None
  _globals['_VAULTDEPOSITMESSAGE'].fields_by_name['vault_account']._serialized_options = b'\220\265\030\001'
  _globals['_VAULTDEPOSITMESSAGE'].fields_by_name['deposit_amount']._loaded_options = None
  _globals['_VAULTDEPOSITMESSAGE'].fields_by_name['deposit_amount']._serialized_options = b'\210\265\030\001'
  _globals['_SETVAULTDEPOSITMESSAGE'].fields_by_name['vault_account']._loaded_options = None
  _globals['_SETVAULTDEPOSITMESSAGE'].fields_by_name['vault_account']._serialized_options = b'\220\265\030\001'
  _globals['_SETVAULTAUTOCLOSEONWITHDRAWMESSAGE'].fields_by_name['vault_account']._loaded_options = None
  _globals['_SETVAULTAUTOCLOSEONWITHDRAWMESSAGE'].fields_by_name['vault_account']._serialized_options = b'\220\265\030\001'
  _globals['_PREPARECLOSEVAULTMESSAGE'].fields_by_name['vault_account']._loaded_options = None
  _globals['_PREPARECLOSEVAULTMESSAGE'].fields_by_name['vault_account']._serialized_options = b'\220\265\030\001'
  _globals['_EXECUTECLOSEVAULTMESSAGE'].fields_by_name['vault_account']._loaded_options = None
  _globals['_EXECUTECLOSEVAULTMESSAGE'].fields_by_name['vault_account']._serialized_options = b'\220\265\030\001'
  _globals['_MAINTAINVAULTMESSAGE'].fields_by_name['vault_account']._loaded_options = None
  _globals['_MAINTAINVAULTMESSAGE'].fields_by_name['vault_account']._serialized_options = b'\220\265\030\001'
  _globals['_VAULTWITHDRAWMESSAGE'].fields_by_name['vault_account']._loaded_options = None
  _globals['_VAULTWITHDRAWMESSAGE'].fields_by_name['vault_account']._serialized_options = b'\220\265\030\001'
  _globals['_VAULTWITHDRAWMESSAGE'].fields_by_name['withdraw_amount']._loaded_options = None
  _globals['_VAULTWITHDRAWMESSAGE'].fields_by_name['withdraw_amount']._serialized_options = b'\210\265\030\001'
  _globals['_VAULTSTATUS']._serialized_start=718
  _globals['_VAULTSTATUS']._serialized_end=837
  _globals['_VAULTCONFIGMESSAGE']._serialized_start=61
  _globals['_VAULTCONFIGMESSAGE']._serialized_end=117
  _globals['_CREATEVAULTMESSAGE']._serialized_start=119
  _globals['_CREATEVAULTMESSAGE']._serialized_end=204
  _globals['_VAULTDEPOSITMESSAGE']._serialized_start=206
  _globals['_VAULTDEPOSITMESSAGE']._serialized_end=286
  _globals['_SETVAULTDEPOSITMESSAGE']._serialized_start=288
  _globals['_SETVAULTDEPOSITMESSAGE']._serialized_end=366
  _globals['_SETVAULTAUTOCLOSEONWITHDRAWMESSAGE']._serialized_start=368
  _globals['_SETVAULTAUTOCLOSEONWITHDRAWMESSAGE']._serialized_end=465
  _globals['_PREPARECLOSEVAULTMESSAGE']._serialized_start=467
  _globals['_PREPARECLOSEVAULTMESSAGE']._serialized_end=522
  _globals['_EXECUTECLOSEVAULTMESSAGE']._serialized_start=524
  _globals['_EXECUTECLOSEVAULTMESSAGE']._serialized_end=579
  _globals['_MAINTAINVAULTMESSAGE']._serialized_start=581
  _globals['_MAINTAINVAULTMESSAGE']._serialized_end=632
  _globals['_VAULTWITHDRAWMESSAGE']._serialized_start=634
  _globals['_VAULTWITHDRAWMESSAGE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
