# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/snapshot/base_metadata_custom.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'schema/snapshot/base_metadata_custom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*schema/snapshot/base_metadata_custom.proto\x12\x15share.schema.snapshot\"`\n\x11RiskLimitSnapshot\x12\x13\n\x0brange_lower\x18\x01 \x01(\t\x12\x13\n\x0brange_upper\x18\x02 \x01(\t\x12\x0b\n\x03mmr\x18\x03 \x01(\t\x12\x14\n\x0cmax_leverage\x18\x04 \x01(\r\"Z\n\rRiskLimitsRow\x12\n\n\x02id\x18\x01 \x01(\r\x12=\n\x0brisk_limits\x18\x02 \x03(\x0b\x32(.share.schema.snapshot.RiskLimitSnapshotB4Z2github.com/exc-works/caishen/share/schema/snapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.snapshot.base_metadata_custom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/exc-works/caishen/share/schema/snapshot'
  _globals['_RISKLIMITSNAPSHOT']._serialized_start=69
  _globals['_RISKLIMITSNAPSHOT']._serialized_end=165
  _globals['_RISKLIMITSROW']._serialized_start=167
  _globals['_RISKLIMITSROW']._serialized_end=257
# @@protoc_insertion_point(module_scope)
