# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/snapshot/positions_custom.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'schema/snapshot/positions_custom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&schema/snapshot/positions_custom.proto\x12\x15share.schema.snapshot\"=\n\x13\x42idAskPriceSnapshot\x12\x0b\n\x03\x62id\x18\x01 \x01(\t\x12\x0b\n\x03\x61sk\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\"j\n\x17\x42idAskPriceListSnapshot\x12\x38\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32*.share.schema.snapshot.BidAskPriceSnapshot\x12\x15\n\rcurrent_index\x18\x02 \x01(\x05\x42\x34Z2github.com/exc-works/caishen/share/schema/snapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.snapshot.positions_custom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/exc-works/caishen/share/schema/snapshot'
  _globals['_BIDASKPRICESNAPSHOT']._serialized_start=65
  _globals['_BIDASKPRICESNAPSHOT']._serialized_end=126
  _globals['_BIDASKPRICELISTSNAPSHOT']._serialized_start=128
  _globals['_BIDASKPRICELISTSNAPSHOT']._serialized_end=234
# @@protoc_insertion_point(module_scope)
