# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/balance.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'api/balance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi/balance.proto\x12\x07\x62\x61lance\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"\x83\x01\n\x13ListBalancesRequest\x12l\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0c\x42[\xc8\xde\x1f\x00\xda\xde\x1f.github.com/ethereum/go-ethereum/common.Address\xf2\xde\x1f!form:\"account\" binding:\"required\"\"B\n\x14ListBalancesResponse\x12*\n\x08\x62\x61lances\x18\x01 \x03(\x0b\x32\x18.balance.BalanceResponse\"\xa8\x03\n\x0f\x42\x61lanceResponse\x12\x10\n\x08token_id\x18\x01 \x01(\r\x12P\n\x06wallet\x18\x02 \x01(\tB@\xc8\xde\x1f\x00\xda\xde\x1f\x38github.com/exc-works/caishen/common/math/decimal.Decimal\x12\x62\n\x18isolated_position_frozen\x18\x03 \x01(\tB@\xc8\xde\x1f\x00\xda\xde\x1f\x38github.com/exc-works/caishen/common/math/decimal.Decimal\x12_\n\x15isolated_order_frozen\x18\x04 \x01(\tB@\xc8\xde\x1f\x00\xda\xde\x1f\x38github.com/exc-works/caishen/common/math/decimal.Decimal\x12\\\n\x12\x63ross_order_frozen\x18\x05 \x01(\tB@\xc8\xde\x1f\x00\xda\xde\x1f\x38github.com/exc-works/caishen/common/math/decimal.Decimal\x12\x0e\n\x06symbol\x18\x06 \x01(\t2l\n\x07\x42\x61lance\x12\x61\n\x0cListBalances\x12\x1c.balance.ListBalancesRequest\x1a\x1d.balance.ListBalancesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/v1/balancesB(Z&github.com/exc-works/caishen/api/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.balance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/exc-works/caishen/api/types'
  _globals['_LISTBALANCESREQUEST'].fields_by_name['account']._loaded_options = None
  _globals['_LISTBALANCESREQUEST'].fields_by_name['account']._serialized_options = b'\310\336\037\000\332\336\037.github.com/ethereum/go-ethereum/common.Address\362\336\037!form:\"account\" binding:\"required\"'
  _globals['_BALANCERESPONSE'].fields_by_name['wallet']._loaded_options = None
  _globals['_BALANCERESPONSE'].fields_by_name['wallet']._serialized_options = b'\310\336\037\000\332\336\0378github.com/exc-works/caishen/common/math/decimal.Decimal'
  _globals['_BALANCERESPONSE'].fields_by_name['isolated_position_frozen']._loaded_options = None
  _globals['_BALANCERESPONSE'].fields_by_name['isolated_position_frozen']._serialized_options = b'\310\336\037\000\332\336\0378github.com/exc-works/caishen/common/math/decimal.Decimal'
  _globals['_BALANCERESPONSE'].fields_by_name['isolated_order_frozen']._loaded_options = None
  _globals['_BALANCERESPONSE'].fields_by_name['isolated_order_frozen']._serialized_options = b'\310\336\037\000\332\336\0378github.com/exc-works/caishen/common/math/decimal.Decimal'
  _globals['_BALANCERESPONSE'].fields_by_name['cross_order_frozen']._loaded_options = None
  _globals['_BALANCERESPONSE'].fields_by_name['cross_order_frozen']._serialized_options = b'\310\336\037\000\332\336\0378github.com/exc-works/caishen/common/math/decimal.Decimal'
  _globals['_BALANCE'].methods_by_name['ListBalances']._loaded_options = None
  _globals['_BALANCE'].methods_by_name['ListBalances']._serialized_options = b'\202\323\344\223\002\016\022\014/v1/balances'
  _globals['_LISTBALANCESREQUEST']._serialized_start=83
  _globals['_LISTBALANCESREQUEST']._serialized_end=214
  _globals['_LISTBALANCESRESPONSE']._serialized_start=216
  _globals['_LISTBALANCESRESPONSE']._serialized_end=282
  _globals['_BALANCERESPONSE']._serialized_start=285
  _globals['_BALANCERESPONSE']._serialized_end=709
  _globals['_BALANCE']._serialized_start=711
  _globals['_BALANCE']._serialized_end=819
# @@protoc_insertion_point(module_scope)
