# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/block.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'api/block.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61pi/block.proto\x12\x02tx\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"\x14\n\x12LatestBlockRequest\"7\n\x13LatestBlockResponse\x12 \n\x05\x62lock\x18\x01 \x01(\x0b\x32\x11.tx.BlockResponse\"\xee\x01\n\rBlockResponse\x12\x0e\n\x06number\x18\x01 \x01(\x04\x12H\n\x08proposer\x18\x02 \x01(\x0c\x42\x36\xc8\xde\x1f\x00\xda\xde\x1f.github.com/ethereum/go-ethereum/common.Address\x12\x41\n\x04hash\x18\x03 \x01(\x0c\x42\x33\xc8\xde\x1f\x00\xda\xde\x1f+github.com/ethereum/go-ethereum/common.Hash\x12\x0c\n\x04time\x18\x04 \x01(\x03\x12\x19\n\x11start_sequence_id\x18\x05 \x01(\x04\x12\x17\n\x0f\x65nd_sequence_id\x18\x06 \x01(\x04\x32j\n\x05\x42lock\x12\x61\n\x0bLatestBlock\x12\x16.tx.LatestBlockRequest\x1a\x17.tx.LatestBlockResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/explorer/latest-blockB(Z&github.com/exc-works/caishen/api/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.block_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/exc-works/caishen/api/types'
  _globals['_BLOCKRESPONSE'].fields_by_name['proposer']._loaded_options = None
  _globals['_BLOCKRESPONSE'].fields_by_name['proposer']._serialized_options = b'\310\336\037\000\332\336\037.github.com/ethereum/go-ethereum/common.Address'
  _globals['_BLOCKRESPONSE'].fields_by_name['hash']._loaded_options = None
  _globals['_BLOCKRESPONSE'].fields_by_name['hash']._serialized_options = b'\310\336\037\000\332\336\037+github.com/ethereum/go-ethereum/common.Hash'
  _globals['_BLOCK'].methods_by_name['LatestBlock']._loaded_options = None
  _globals['_BLOCK'].methods_by_name['LatestBlock']._serialized_options = b'\202\323\344\223\002\033\022\031/v1/explorer/latest-block'
  _globals['_LATESTBLOCKREQUEST']._serialized_start=75
  _globals['_LATESTBLOCKREQUEST']._serialized_end=95
  _globals['_LATESTBLOCKRESPONSE']._serialized_start=97
  _globals['_LATESTBLOCKRESPONSE']._serialized_end=152
  _globals['_BLOCKRESPONSE']._serialized_start=155
  _globals['_BLOCKRESPONSE']._serialized_end=393
  _globals['_BLOCK']._serialized_start=395
  _globals['_BLOCK']._serialized_end=501
# @@protoc_insertion_point(module_scope)
