# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/candle.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'api/candle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61pi/candle.proto\x12\x06\x63\x61ndle\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"\x18\n\x16QueryServerTimeRequest\"9\n\x17QueryServerTimeResponse\x12\x1e\n\x16server_time_unix_milli\x18\x01 \x01(\x03\"\xee\x01\n\x15QueryUDFResultRequest\x12\x34\n\x06symbol\x18\x01 \x01(\tB$\xf2\xde\x1f form:\"symbol\" binding:\"required\"\x12\x1d\n\x04\x66rom\x18\x02 \x01(\x03\x42\x0f\xf2\xde\x1f\x0b\x66orm:\"from\"\x12\x19\n\x02to\x18\x03 \x01(\x03\x42\r\xf2\xde\x1f\tform:\"to\"\x12<\n\nresolution\x18\x04 \x01(\tB(\xf2\xde\x1f$form:\"resolution\" binding:\"required\"\x12\'\n\tcountback\x18\x05 \x01(\x03\x42\x14\xf2\xde\x1f\x10\x66orm:\"countback\"\"u\n\x16QueryUDFResultResponse\x12\t\n\x01s\x18\x01 \x01(\t\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\t\x12\t\n\x01t\x18\x03 \x03(\x03\x12\t\n\x01\x63\x18\x04 \x03(\t\x12\t\n\x01o\x18\x05 \x03(\t\x12\t\n\x01h\x18\x06 \x03(\t\x12\t\n\x01l\x18\x07 \x03(\t\x12\t\n\x01v\x18\x08 \x03(\t2\xc8\x03\n\x06\x43\x61ndle\x12h\n\x0fQueryServerTime\x12\x1e.candle.QueryServerTimeRequest\x1a\x1f.candle.QueryServerTimeResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/v1/udf/time\x12h\n\x0eQueryUDFResult\x12\x1d.candle.QueryUDFResultRequest\x1a\x1e.candle.QueryUDFResultResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/udf/history\x12u\n\x15QueryIndexPriceResult\x12\x1d.candle.QueryUDFResultRequest\x1a\x1e.candle.QueryUDFResultResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/udf/index-history\x12s\n\x14QueryMarkPriceResult\x12\x1d.candle.QueryUDFResultRequest\x1a\x1e.candle.QueryUDFResultResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/udf/mark-historyB(Z&github.com/exc-works/caishen/api/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.candle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/exc-works/caishen/api/types'
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['symbol']._loaded_options = None
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['symbol']._serialized_options = b'\362\336\037 form:\"symbol\" binding:\"required\"'
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['from']._loaded_options = None
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['from']._serialized_options = b'\362\336\037\013form:\"from\"'
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['to']._loaded_options = None
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['to']._serialized_options = b'\362\336\037\tform:\"to\"'
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['resolution']._loaded_options = None
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['resolution']._serialized_options = b'\362\336\037$form:\"resolution\" binding:\"required\"'
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['countback']._loaded_options = None
  _globals['_QUERYUDFRESULTREQUEST'].fields_by_name['countback']._serialized_options = b'\362\336\037\020form:\"countback\"'
  _globals['_CANDLE'].methods_by_name['QueryServerTime']._loaded_options = None
  _globals['_CANDLE'].methods_by_name['QueryServerTime']._serialized_options = b'\202\323\344\223\002\016\022\014/v1/udf/time'
  _globals['_CANDLE'].methods_by_name['QueryUDFResult']._loaded_options = None
  _globals['_CANDLE'].methods_by_name['QueryUDFResult']._serialized_options = b'\202\323\344\223\002\021\022\017/v1/udf/history'
  _globals['_CANDLE'].methods_by_name['QueryIndexPriceResult']._loaded_options = None
  _globals['_CANDLE'].methods_by_name['QueryIndexPriceResult']._serialized_options = b'\202\323\344\223\002\027\022\025/v1/udf/index-history'
  _globals['_CANDLE'].methods_by_name['QueryMarkPriceResult']._loaded_options = None
  _globals['_CANDLE'].methods_by_name['QueryMarkPriceResult']._serialized_options = b'\202\323\344\223\002\026\022\024/v1/udf/mark-history'
  _globals['_QUERYSERVERTIMEREQUEST']._serialized_start=80
  _globals['_QUERYSERVERTIMEREQUEST']._serialized_end=104
  _globals['_QUERYSERVERTIMERESPONSE']._serialized_start=106
  _globals['_QUERYSERVERTIMERESPONSE']._serialized_end=163
  _globals['_QUERYUDFRESULTREQUEST']._serialized_start=166
  _globals['_QUERYUDFRESULTREQUEST']._serialized_end=404
  _globals['_QUERYUDFRESULTRESPONSE']._serialized_start=406
  _globals['_QUERYUDFRESULTRESPONSE']._serialized_end=523
  _globals['_CANDLE']._serialized_start=526
  _globals['_CANDLE']._serialized_end=982
# @@protoc_insertion_point(module_scope)
