# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/faucet.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'api/faucet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61pi/faucet.proto\x12\x06\x66\x61ucet\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"L\n\x12\x46\x61ucetClaimRequest\x12\x36\n\x07\x61\x63\x63ount\x18\x01 \x01(\tB%\xf2\xde\x1f!form:\"account\" binding:\"required\"\"2\n\x13\x46\x61ucetClaimResponse\x12\x1b\n\x07tx_hash\x18\x01 \x01(\tB\n\xea\xde\x1f\x06txHash\"M\n\x13\x46\x61ucetStatusRequest\x12\x36\n\x07\x61\x63\x63ount\x18\x01 \x01(\tB%\xf2\xde\x1f!form:\"account\" binding:\"required\"\"Q\n\x14\x46\x61ucetStatusResponse\x12\x1c\n\x07\x63laimed\x18\x01 \x01(\x08\x42\x0b\xea\xde\x1f\x07\x63laimed\x12\x1b\n\x07tx_hash\x18\x02 \x01(\tB\n\xea\xde\x1f\x06txHash2\xca\x01\n\x06\x46\x61ucet\x12]\n\x05\x43laim\x12\x1a.faucet.FaucetClaimRequest\x1a\x1b.faucet.FaucetClaimResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/faucet/claim:\x01*\x12\x61\n\tGetStatus\x12\x1b.faucet.FaucetStatusRequest\x1a\x1c.faucet.FaucetStatusResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/faucet/statusB(Z&github.com/exc-works/caishen/api/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.faucet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/exc-works/caishen/api/types'
  _globals['_FAUCETCLAIMREQUEST'].fields_by_name['account']._loaded_options = None
  _globals['_FAUCETCLAIMREQUEST'].fields_by_name['account']._serialized_options = b'\362\336\037!form:\"account\" binding:\"required\"'
  _globals['_FAUCETCLAIMRESPONSE'].fields_by_name['tx_hash']._loaded_options = None
  _globals['_FAUCETCLAIMRESPONSE'].fields_by_name['tx_hash']._serialized_options = b'\352\336\037\006txHash'
  _globals['_FAUCETSTATUSREQUEST'].fields_by_name['account']._loaded_options = None
  _globals['_FAUCETSTATUSREQUEST'].fields_by_name['account']._serialized_options = b'\362\336\037!form:\"account\" binding:\"required\"'
  _globals['_FAUCETSTATUSRESPONSE'].fields_by_name['claimed']._loaded_options = None
  _globals['_FAUCETSTATUSRESPONSE'].fields_by_name['claimed']._serialized_options = b'\352\336\037\007claimed'
  _globals['_FAUCETSTATUSRESPONSE'].fields_by_name['tx_hash']._loaded_options = None
  _globals['_FAUCETSTATUSRESPONSE'].fields_by_name['tx_hash']._serialized_options = b'\352\336\037\006txHash'
  _globals['_FAUCET'].methods_by_name['Claim']._loaded_options = None
  _globals['_FAUCET'].methods_by_name['Claim']._serialized_options = b'\202\323\344\223\002\025\"\020/v1/faucet/claim:\001*'
  _globals['_FAUCET'].methods_by_name['GetStatus']._loaded_options = None
  _globals['_FAUCET'].methods_by_name['GetStatus']._serialized_options = b'\202\323\344\223\002\023\022\021/v1/faucet/status'
  _globals['_FAUCETCLAIMREQUEST']._serialized_start=80
  _globals['_FAUCETCLAIMREQUEST']._serialized_end=156
  _globals['_FAUCETCLAIMRESPONSE']._serialized_start=158
  _globals['_FAUCETCLAIMRESPONSE']._serialized_end=208
  _globals['_FAUCETSTATUSREQUEST']._serialized_start=210
  _globals['_FAUCETSTATUSREQUEST']._serialized_end=287
  _globals['_FAUCETSTATUSRESPONSE']._serialized_start=289
  _globals['_FAUCETSTATUSRESPONSE']._serialized_end=370
  _globals['_FAUCET']._serialized_start=373
  _globals['_FAUCET']._serialized_end=575
# @@protoc_insertion_point(module_scope)
