# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/fee_tier.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'api/fee_tier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61pi/fee_tier.proto\x12\x08\x66\x65\x65_tier\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"\x1a\n\x18GetFeeTierProfileRequest\"I\n\x19GetFeeTierProfileResponse\x12,\n\tfee_tiers\x18\x01 \x03(\x0b\x32\x19.fee_tier.FeeTierResponse\"\xc1\x01\n\x0f\x46\x65\x65TierResponse\x12\x0c\n\x04tier\x18\x01 \x01(\r\x12O\n\x05taker\x18\x02 \x01(\tB@\xc8\xde\x1f\x00\xda\xde\x1f\x38github.com/exc-works/caishen/common/math/decimal.Decimal\x12O\n\x05maker\x18\x03 \x01(\tB@\xc8\xde\x1f\x00\xda\xde\x1f\x38github.com/exc-works/caishen/common/math/decimal.Decimal2~\n\x07\x46\x65\x65Tier\x12s\n\x11GetFeeTierProfile\x12\".fee_tier.GetFeeTierProfileRequest\x1a#.fee_tier.GetFeeTierProfileResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/fee-tiersB(Z&github.com/exc-works/caishen/api/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.fee_tier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/exc-works/caishen/api/types'
  _globals['_FEETIERRESPONSE'].fields_by_name['taker']._loaded_options = None
  _globals['_FEETIERRESPONSE'].fields_by_name['taker']._serialized_options = b'\310\336\037\000\332\336\0378github.com/exc-works/caishen/common/math/decimal.Decimal'
  _globals['_FEETIERRESPONSE'].fields_by_name['maker']._loaded_options = None
  _globals['_FEETIERRESPONSE'].fields_by_name['maker']._serialized_options = b'\310\336\037\000\332\336\0378github.com/exc-works/caishen/common/math/decimal.Decimal'
  _globals['_FEETIER'].methods_by_name['GetFeeTierProfile']._loaded_options = None
  _globals['_FEETIER'].methods_by_name['GetFeeTierProfile']._serialized_options = b'\202\323\344\223\002\017\022\r/v1/fee-tiers'
  _globals['_GETFEETIERPROFILEREQUEST']._serialized_start=84
  _globals['_GETFEETIERPROFILEREQUEST']._serialized_end=110
  _globals['_GETFEETIERPROFILERESPONSE']._serialized_start=112
  _globals['_GETFEETIERPROFILERESPONSE']._serialized_end=185
  _globals['_FEETIERRESPONSE']._serialized_start=188
  _globals['_FEETIERRESPONSE']._serialized_end=381
  _globals['_FEETIER']._serialized_start=383
  _globals['_FEETIER']._serialized_end=509
# @@protoc_insertion_point(module_scope)
