# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/geo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api/geo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rapi/geo.proto\x12\x03geo\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"\x14\n\x12GetGeoBlockRequest\"\x81\x01\n\x13GetGeoBlockResponse\x12\x1c\n\x07\x62locked\x18\x01 \x01(\x08\x42\x0b\xea\xde\x1f\x07\x62locked\x12\x12\n\x02ip\x18\x02 \x01(\tB\x06\xea\xde\x1f\x02ip\x12\x1c\n\x07\x63ountry\x18\x03 \x01(\tB\x0b\xea\xde\x1f\x07\x63ountry\x12\x1a\n\x06region\x18\x04 \x01(\tB\n\xea\xde\x1f\x06region2^\n\x03Geo\x12W\n\x0bGetGeoBlock\x12\x17.geo.GetGeoBlockRequest\x1a\x18.geo.GetGeoBlockResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/geo-blockB(Z&github.com/exc-works/caishen/api/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.geo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/exc-works/caishen/api/types'
  _globals['_GETGEOBLOCKRESPONSE'].fields_by_name['blocked']._loaded_options = None
  _globals['_GETGEOBLOCKRESPONSE'].fields_by_name['blocked']._serialized_options = b'\352\336\037\007blocked'
  _globals['_GETGEOBLOCKRESPONSE'].fields_by_name['ip']._loaded_options = None
  _globals['_GETGEOBLOCKRESPONSE'].fields_by_name['ip']._serialized_options = b'\352\336\037\002ip'
  _globals['_GETGEOBLOCKRESPONSE'].fields_by_name['country']._loaded_options = None
  _globals['_GETGEOBLOCKRESPONSE'].fields_by_name['country']._serialized_options = b'\352\336\037\007country'
  _globals['_GETGEOBLOCKRESPONSE'].fields_by_name['region']._loaded_options = None
  _globals['_GETGEOBLOCKRESPONSE'].fields_by_name['region']._serialized_options = b'\352\336\037\006region'
  _globals['_GEO'].methods_by_name['GetGeoBlock']._loaded_options = None
  _globals['_GEO'].methods_by_name['GetGeoBlock']._serialized_options = b'\202\323\344\223\002\017\022\r/v1/geo-block'
  _globals['_GETGEOBLOCKREQUEST']._serialized_start=74
  _globals['_GETGEOBLOCKREQUEST']._serialized_end=94
  _globals['_GETGEOBLOCKRESPONSE']._serialized_start=97
  _globals['_GETGEOBLOCKRESPONSE']._serialized_end=226
  _globals['_GEO']._serialized_start=228
  _globals['_GEO']._serialized_end=322
# @@protoc_insertion_point(module_scope)
