# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/l2book.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'api/l2book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61pi/l2book.proto\x12\x06l2book\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n\x10GetL2bookRequest\x12\x34\n\x06symbol\x18\x01 \x01(\tB$\xf2\xde\x1f form:\"symbol\" binding:\"required\"\x12\x31\n\x0etrading_domain\x18\x04 \x01(\tB\x19\xf2\xde\x1f\x15\x66orm:\"trading_domain\"\x12\x42\n\x11\x61ggregation_level\x18\x02 \x01(\tB\'\xf2\xde\x1f#form:\"aggregation_level,default=1x\"\x12K\n\x05limit\x18\x03 \x01(\x05\x42<\xf2\xde\x1f\x38\x66orm:\"limit,default=1\" binding:\"omitempty,min=1,max=400\"\"\xcf\x01\n\x11GetL2bookResponse\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12V\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\'\x18\x01\xc8\xde\x1f\x00\xf2\xde\x1f\x19json:\"timestamp,omitzero\"\x90\xdf\x1f\x01\x12\n\n\x02ts\x18\x05 \x01(\x03\x12!\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x13.l2book.L2bookLevel\x12!\n\x04\x62ids\x18\x04 \x03(\x0b\x32\x13.l2book.L2bookLevel\"\x86\x01\n\x0bL2bookLevel\x12;\n\x05price\x18\x01 \x01(\tB,\xc8\xde\x1f\x00\xda\xde\x1f$github.com/exc-works/decimal.Decimal\x12:\n\x04size\x18\x02 \x01(\tB,\xc8\xde\x1f\x00\xda\xde\x1f$github.com/exc-works/decimal.Decimal2^\n\x06L2book\x12T\n\tGetL2book\x12\x18.l2book.GetL2bookRequest\x1a\x19.l2book.GetL2bookResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/l2bookB(Z&github.com/exc-works/caishen/api/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.l2book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/exc-works/caishen/api/types'
  _globals['_GETL2BOOKREQUEST'].fields_by_name['symbol']._loaded_options = None
  _globals['_GETL2BOOKREQUEST'].fields_by_name['symbol']._serialized_options = b'\362\336\037 form:\"symbol\" binding:\"required\"'
  _globals['_GETL2BOOKREQUEST'].fields_by_name['trading_domain']._loaded_options = None
  _globals['_GETL2BOOKREQUEST'].fields_by_name['trading_domain']._serialized_options = b'\362\336\037\025form:\"trading_domain\"'
  _globals['_GETL2BOOKREQUEST'].fields_by_name['aggregation_level']._loaded_options = None
  _globals['_GETL2BOOKREQUEST'].fields_by_name['aggregation_level']._serialized_options = b'\362\336\037#form:\"aggregation_level,default=1x\"'
  _globals['_GETL2BOOKREQUEST'].fields_by_name['limit']._loaded_options = None
  _globals['_GETL2BOOKREQUEST'].fields_by_name['limit']._serialized_options = b'\362\336\0378form:\"limit,default=1\" binding:\"omitempty,min=1,max=400\"'
  _globals['_GETL2BOOKRESPONSE'].fields_by_name['timestamp']._loaded_options = None
  _globals['_GETL2BOOKRESPONSE'].fields_by_name['timestamp']._serialized_options = b'\030\001\310\336\037\000\362\336\037\031json:\"timestamp,omitzero\"\220\337\037\001'
  _globals['_L2BOOKLEVEL'].fields_by_name['price']._loaded_options = None
  _globals['_L2BOOKLEVEL'].fields_by_name['price']._serialized_options = b'\310\336\037\000\332\336\037$github.com/exc-works/decimal.Decimal'
  _globals['_L2BOOKLEVEL'].fields_by_name['size']._loaded_options = None
  _globals['_L2BOOKLEVEL'].fields_by_name['size']._serialized_options = b'\310\336\037\000\332\336\037$github.com/exc-works/decimal.Decimal'
  _globals['_L2BOOK'].methods_by_name['GetL2book']._loaded_options = None
  _globals['_L2BOOK'].methods_by_name['GetL2book']._serialized_options = b'\202\323\344\223\002\014\022\n/v1/l2book'
  _globals['_GETL2BOOKREQUEST']._serialized_start=114
  _globals['_GETL2BOOKREQUEST']._serialized_end=382
  _globals['_GETL2BOOKRESPONSE']._serialized_start=385
  _globals['_GETL2BOOKRESPONSE']._serialized_end=592
  _globals['_L2BOOKLEVEL']._serialized_start=595
  _globals['_L2BOOKLEVEL']._serialized_end=729
  _globals['_L2BOOK']._serialized_start=731
  _globals['_L2BOOK']._serialized_end=825
# @@protoc_insertion_point(module_scope)
