# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/risk.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'api/risk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pi/risk.proto\x12\x04risk\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"A\n\x11RiskLimitsRequest\x12,\n\x02id\x18\x01 \x01(\rB \xf2\xde\x1f\x1c\x66orm:\"id\" binding:\"required\"\"\xc2\x01\n\x12RiskLimitsResponse\x12\n\n\x02id\x18\x01 \x01(\r\x12X\n\nrisk_limit\x18\x02 \x01(\tBD\xc8\xde\x1f\x00\xda\xde\x1f<github.com/exc-works/caishen/engine/runtime/types.RiskLimits\x12\"\n\ncreated_at\x18\x03 \x01(\x03\x42\x0e\xea\xde\x1f\ncreated_at\x12\"\n\nupdated_at\x18\x04 \x01(\x03\x42\x0e\xea\xde\x1f\nupdated_at2e\n\nRiskLimits\x12W\n\tRiskLimit\x12\x17.risk.RiskLimitsRequest\x1a\x18.risk.RiskLimitsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/risk-limitsB(Z&github.com/exc-works/caishen/api/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.risk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/exc-works/caishen/api/types'
  _globals['_RISKLIMITSREQUEST'].fields_by_name['id']._loaded_options = None
  _globals['_RISKLIMITSREQUEST'].fields_by_name['id']._serialized_options = b'\362\336\037\034form:\"id\" binding:\"required\"'
  _globals['_RISKLIMITSRESPONSE'].fields_by_name['risk_limit']._loaded_options = None
  _globals['_RISKLIMITSRESPONSE'].fields_by_name['risk_limit']._serialized_options = b'\310\336\037\000\332\336\037<github.com/exc-works/caishen/engine/runtime/types.RiskLimits'
  _globals['_RISKLIMITSRESPONSE'].fields_by_name['created_at']._loaded_options = None
  _globals['_RISKLIMITSRESPONSE'].fields_by_name['created_at']._serialized_options = b'\352\336\037\ncreated_at'
  _globals['_RISKLIMITSRESPONSE'].fields_by_name['updated_at']._loaded_options = None
  _globals['_RISKLIMITSRESPONSE'].fields_by_name['updated_at']._serialized_options = b'\352\336\037\nupdated_at'
  _globals['_RISKLIMITS'].methods_by_name['RiskLimit']._loaded_options = None
  _globals['_RISKLIMITS'].methods_by_name['RiskLimit']._serialized_options = b'\202\323\344\223\002\021\022\017/v1/risk-limits'
  _globals['_RISKLIMITSREQUEST']._serialized_start=76
  _globals['_RISKLIMITSREQUEST']._serialized_end=141
  _globals['_RISKLIMITSRESPONSE']._serialized_start=144
  _globals['_RISKLIMITSRESPONSE']._serialized_end=338
  _globals['_RISKLIMITS']._serialized_start=340
  _globals['_RISKLIMITS']._serialized_end=441
# @@protoc_insertion_point(module_scope)
