# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/token.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'api/token.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61pi/token.proto\x12\x05token\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"\x13\n\x11ListTokensRequest\"6\n\x12ListTokensResponse\x12 \n\x06tokens\x18\x01 \x03(\x0b\x32\x10.token.TokenInfo\"\xd2\x01\n\tTokenInfo\x12\x12\n\x02id\x18\x01 \x01(\rB\x06\xea\xde\x1f\x02id\x12\x16\n\x04name\x18\x02 \x01(\tB\x08\xea\xde\x1f\x04name\x12\x1a\n\x06symbol\x18\x03 \x01(\tB\n\xea\xde\x1f\x06symbol\x12\x1e\n\x08\x64\x65\x63imals\x18\x04 \x01(\rB\x0c\xea\xde\x1f\x08\x64\x65\x63imals\x12\x1a\n\x06\x61vatar\x18\x05 \x01(\tB\n\xea\xde\x1f\x06\x61vatar\x12\x41\n\rchain_configs\x18\x06 \x03(\x0b\x32\x17.token.TokenChainConfigB\x11\xea\xde\x1f\rchain_configs\"\x90\x04\n\x10TokenChainConfig\x12\x1e\n\x08\x63hain_id\x18\x01 \x01(\x04\x42\x0c\xea\xde\x1f\x08\x63hain_id\x12\"\n\nchain_name\x18\x02 \x01(\tB\x0e\xea\xde\x1f\nchain_name\x12\x1e\n\x08\x63ontract\x18\x03 \x01(\tB\x0c\xea\xde\x1f\x08\x63ontract\x12P\n\x0bmin_deposit\x18\x04 \x01(\tB;\xc8\xde\x1f\x00\xda\xde\x1f$github.com/exc-works/decimal.Decimal\xea\xde\x1f\x0bmin_deposit\x12\x34\n\x13\x62lock_confirmations\x18\x05 \x01(\rB\x17\xea\xde\x1f\x13\x62lock_confirmations\x12\x32\n\x12\x64\x65posit_enabled_at\x18\x06 \x01(\x03\x42\x16\xea\xde\x1f\x12\x64\x65posit_enabled_at\x12R\n\x0cmin_withdraw\x18\x07 \x01(\tB<\xc8\xde\x1f\x00\xda\xde\x1f$github.com/exc-works/decimal.Decimal\xea\xde\x1f\x0cmin_withdraw\x12R\n\x0cwithdraw_fee\x18\x08 \x01(\tB<\xc8\xde\x1f\x00\xda\xde\x1f$github.com/exc-works/decimal.Decimal\xea\xde\x1f\x0cwithdraw_fee\x12\x34\n\x13withdraw_enabled_at\x18\t \x01(\x03\x42\x17\xea\xde\x1f\x13withdraw_enabled_at2^\n\x05Token\x12U\n\nListTokens\x12\x18.token.ListTokensRequest\x1a\x19.token.ListTokensResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/tokensB(Z&github.com/exc-works/caishen/api/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.token_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/exc-works/caishen/api/types'
  _globals['_TOKENINFO'].fields_by_name['id']._loaded_options = None
  _globals['_TOKENINFO'].fields_by_name['id']._serialized_options = b'\352\336\037\002id'
  _globals['_TOKENINFO'].fields_by_name['name']._loaded_options = None
  _globals['_TOKENINFO'].fields_by_name['name']._serialized_options = b'\352\336\037\004name'
  _globals['_TOKENINFO'].fields_by_name['symbol']._loaded_options = None
  _globals['_TOKENINFO'].fields_by_name['symbol']._serialized_options = b'\352\336\037\006symbol'
  _globals['_TOKENINFO'].fields_by_name['decimals']._loaded_options = None
  _globals['_TOKENINFO'].fields_by_name['decimals']._serialized_options = b'\352\336\037\010decimals'
  _globals['_TOKENINFO'].fields_by_name['avatar']._loaded_options = None
  _globals['_TOKENINFO'].fields_by_name['avatar']._serialized_options = b'\352\336\037\006avatar'
  _globals['_TOKENINFO'].fields_by_name['chain_configs']._loaded_options = None
  _globals['_TOKENINFO'].fields_by_name['chain_configs']._serialized_options = b'\352\336\037\rchain_configs'
  _globals['_TOKENCHAINCONFIG'].fields_by_name['chain_id']._loaded_options = None
  _globals['_TOKENCHAINCONFIG'].fields_by_name['chain_id']._serialized_options = b'\352\336\037\010chain_id'
  _globals['_TOKENCHAINCONFIG'].fields_by_name['chain_name']._loaded_options = None
  _globals['_TOKENCHAINCONFIG'].fields_by_name['chain_name']._serialized_options = b'\352\336\037\nchain_name'
  _globals['_TOKENCHAINCONFIG'].fields_by_name['contract']._loaded_options = None
  _globals['_TOKENCHAINCONFIG'].fields_by_name['contract']._serialized_options = b'\352\336\037\010contract'
  _globals['_TOKENCHAINCONFIG'].fields_by_name['min_deposit']._loaded_options = None
  _globals['_TOKENCHAINCONFIG'].fields_by_name['min_deposit']._serialized_options = b'\310\336\037\000\332\336\037$github.com/exc-works/decimal.Decimal\352\336\037\013min_deposit'
  _globals['_TOKENCHAINCONFIG'].fields_by_name['block_confirmations']._loaded_options = None
  _globals['_TOKENCHAINCONFIG'].fields_by_name['block_confirmations']._serialized_options = b'\352\336\037\023block_confirmations'
  _globals['_TOKENCHAINCONFIG'].fields_by_name['deposit_enabled_at']._loaded_options = None
  _globals['_TOKENCHAINCONFIG'].fields_by_name['deposit_enabled_at']._serialized_options = b'\352\336\037\022deposit_enabled_at'
  _globals['_TOKENCHAINCONFIG'].fields_by_name['min_withdraw']._loaded_options = None
  _globals['_TOKENCHAINCONFIG'].fields_by_name['min_withdraw']._serialized_options = b'\310\336\037\000\332\336\037$github.com/exc-works/decimal.Decimal\352\336\037\014min_withdraw'
  _globals['_TOKENCHAINCONFIG'].fields_by_name['withdraw_fee']._loaded_options = None
  _globals['_TOKENCHAINCONFIG'].fields_by_name['withdraw_fee']._serialized_options = b'\310\336\037\000\332\336\037$github.com/exc-works/decimal.Decimal\352\336\037\014withdraw_fee'
  _globals['_TOKENCHAINCONFIG'].fields_by_name['withdraw_enabled_at']._loaded_options = None
  _globals['_TOKENCHAINCONFIG'].fields_by_name['withdraw_enabled_at']._serialized_options = b'\352\336\037\023withdraw_enabled_at'
  _globals['_TOKEN'].methods_by_name['ListTokens']._loaded_options = None
  _globals['_TOKEN'].methods_by_name['ListTokens']._serialized_options = b'\202\323\344\223\002\014\022\n/v1/tokens'
  _globals['_LISTTOKENSREQUEST']._serialized_start=78
  _globals['_LISTTOKENSREQUEST']._serialized_end=97
  _globals['_LISTTOKENSRESPONSE']._serialized_start=99
  _globals['_LISTTOKENSRESPONSE']._serialized_end=153
  _globals['_TOKENINFO']._serialized_start=156
  _globals['_TOKENINFO']._serialized_end=366
  _globals['_TOKENCHAINCONFIG']._serialized_start=369
  _globals['_TOKENCHAINCONFIG']._serialized_end=897
  _globals['_TOKEN']._serialized_start=899
  _globals['_TOKEN']._serialized_end=993
# @@protoc_insertion_point(module_scope)
